language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token:
        secure: Gf+lPbwB7L/w6DLNFLi0fX7NlnxboWOOvWGvTz8ck963Y15pGE+ZHJaOXQmlTwcjKEIszRsdCI51cwCxV0O6HGM8i2WD6wf++lcGe/oI5cLb4qm0atm+QTWY+9d2TCI5LgejmyB5V9MW/Uvk58ey83CZ45yOhZKet+SihdC9doY=
script:
- npm run cover
after_script:
- npm run publish-coverage
